environment:
  matrix:
    - nodejs_version: "6.9"
    - nodejs_version: "7.4"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test
build: off